### PR TITLE
Update formatting of code snippets in the docs

### PR DESCRIPTION
**Pull request by clowa**
Just a few formatting updates to the code snippets of the docs.

- Fix malformed code blocks
- Add `powershell` code type to powershell code snippets

### CODE REVIEW

**Comment by StartAutomating** [comment]
> Hi, Thank you for your work, but the problem is this is auto-generated from platyps. So on next run it will be overwritten. Since platyps doesn't seem to be on good road to get any updates soon my goal is to switch to https://github.com/StartAutomating/HelpOut, for all of my projects but I need @StartAutomating two small issues.
> 
> The code generated by HelpOut project seems to have proper code snippets handling.

@PrzemyslawKlys please just let me know what you need.

**Comment by PrzemyslawKlys** [comment]
> > Hi, Thank you for your work, but the problem is this is auto-generated from platyps. So on next run it will be overwritten. Since platyps doesn't seem to be on good road to get any updates soon my goal is to switch to https://github.com/StartAutomating/HelpOut, for all of my projects but I need @StartAutomating two small issues.
> 
> > 
> 
> > The code generated by HelpOut project seems to have proper code snippets handling.
> 
> 
> 
> @PrzemyslawKlys please just let me know what you need.

You have two issues opened im your repo by me :-)

**Comment by StartAutomating** [comment]
@PrzemyslawKlys the issues have been fixed, and a new release has been released.

Let me know if you have any more problems, and let me know when you've released (I may be making a gallery soon)

**Comment by clowa** [comment]
> Hi, Thank you for your work, but the problem is this is auto-generated from platyps. So on next run it will be overwritten. Since platyps doesn't seem to be on good road to get any updates soon my goal is to switch to https://github.com/StartAutomating/HelpOut, for all of my projects but I need @StartAutomating two small issues.
> 
> The code generated by HelpOut project seems to have proper code snippets handling.

@PrzemyslawKlys ah damn, I could have thought about that. Whatever, thanks for your Module. It makes using MailKit so easy. Perhaps I find something other to contribute in the future

**Pull request closed without merging**
